services:
  web:
    build:
      context: .
      target: dev
      args:
        NODE_ENV: development
    image: mxtk-site:dev
    container_name: mxtk-site-dev
    command: npm run dev -- -p 2000 -H 0.0.0.0
    ports:
      - "2000:2000"
    environment:
      - NODE_ENV=development
      - PORT=2000
      - HOST=0.0.0.0
      - CORS_ALLOWED_ORIGINS=http://localhost:2000,http://localhost:2001,http://localhost:2002,https://*.ngrok-free.app
      - CSRF_TRUSTED_ORIGINS=http://localhost:2000,http://localhost:2001,http://localhost:2002,https://*.ngrok-free.app
      - NEXT_PUBLIC_BASE_PATH=
      - NEXT_PUBLIC_ASSET_PREFIX=
    env_file:
      - .env.dev
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:2000" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - default
      - ngrok-shared

  # ─── Shared Dev Proxy (for sharing all services via ngrok) ─────────────────
  proxy:
    image: nginx:alpine
    container_name: dev-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    networks:
      - default
      - ngrok-shared

  # ─── Ngrok (shares the proxy) ──────────────────────────────────────────
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok-external-proxy
    restart: unless-stopped
    environment:
      - NGROK_AUTHTOKEN=2ys22TN5DNODqFfkisK86gaBDN1_3cyhFAiU8Zce19LjiRkFg
    ports:
      - "4040:4040" # expose the Web UI / API
    command: ngrok http proxy:80
    networks:
      - default
      - ngrok-shared

networks:
  default: # Internal MXTK network
  ngrok-shared:
    external: true
