services:
  web-prod:
    build:
      context: .
      target: runner
      args:
        NODE_ENV: production
    ports:
      - "2002:2000"
    environment:
      - NODE_ENV=production
      - PORT=2000
      - HOST=0.0.0.0
    env_file:
      - .env.prod
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    networks:
      - default

networks:
  default:
    # Internal MXTK network
