version: '3.8'

services:
  web:
    container_name: mxtk-site-dev
    build: .
    environment:
      - PORT=2000
      - BASIC_AUTH_ENABLED=1       # enable auth over tunnel (optional)
    networks:
      - devproxy

networks:
  devproxy:
    external: true
    name: devproxy

