version: '3.8'

services:
  web:
    container_name: mxtk-site-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "2000:2000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - PORT=2000
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - BASIC_AUTH_ENABLED=0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - devproxy

networks:
  devproxy:
    external: true
    name: devproxy
