services:
  web-staging:
    build:
      context: .
      target: web-prod
      args:
        NODE_ENV: staging
    ports:
      - "2001:2000"
    environment:
      - NODE_ENV=staging
      - PORT=2000
      - HOST=0.0.0.0
    env_file:
      - .env.staging
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - default

networks:
  default:
    # Internal MXTK network
