name: Crawler CI

on:
  push:
    branches: [main, master, develop]
  pull_request:

permissions:
  contents: read

jobs:
  crawl:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Start app (local mode)
        run: |
          chmod +x scripts/smart-build.sh || true
          ./scripts/smart-build.sh local

      - name: Wait for app health
        run: |
          for i in {1..60}; do
            if curl -sf http://localhost:2000/api/health >/dev/null; then
              echo "App healthy"; exit 0; fi; sleep 2; done
          echo "App did not become healthy" >&2
          docker compose ps || true
          docker compose logs --no-color | tail -n 400 || true
          exit 1

      - name: Run crawler (fail on any console warning/error)
        env:
          BASE_URL: http://localhost:2000
          CRAWL_MAX_PAGES: "500"
          CRAWL_NAV_TIMEOUT: "60000"
        run: node tools/test/crawl-regression.mjs

      - name: Upload crawler reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: crawl-reports
          path: tools/debug/output/reports
          if-no-files-found: error

      - name: Cleanup containers
        if: always()
        run: |
          docker compose down -v --remove-orphans || true
